services:
  php-fpm:
    build:
      context: ./docker/php-fpm
      args:
        USER_UID: ${USER_UID}
        USER_GID: ${USER_GID}
        TIMEZONE: ${TIMEZONE}
    container_name: php-fpm
    volumes:
      - ./app:/var/www
    networks:
      - symfony
    extra_hosts:
      - "host.docker.internal:host-gateway"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000"]
      interval: 30s
      retries: 3
      start_period: 5s
      timeout: 10s

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - ./app:/var/www
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./docker/nginx/logs/:/var/log/nginx
    depends_on:
      - php-fpm
    networks:
      - symfony

  mariadb:
    image: mariadb:latest
    container_name: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: symfony
      MYSQL_USER: symfony
      MYSQL_PASSWORD: symfony
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - symfony

networks:
  symfony:
    driver: bridge

volumes:
  mariadb_data:
